### ISSUE TITLE
Reduce count of HTTP proxies during model API invocation

### ISSUE THREAD

**Issue by akharlamov** [legion-platform/legion#101]
This is subtask of #859

At the moment there are too many proxies involved in processing of a single model query. The full processing chain is something like this:

Amazon ELB -> Ingress (Nginx) -> API Edge (Nginx) -> Cluster IP Proxy (Kube Proxy?) -> Model HTTP server (Nginx) -> Python AI Model (uwsgi)

This creates a lot opportunities for things going wrong and increases latency, which is not acceptable in many cases. For instance, AdTech industry requires <20 ms responses, each hop will likly add 2ms and widen latency spread. 

Several possible solutions come to mind:
1. Convert API Edge Server to an Ingress Controller
2. Reconfigure K8S cluster to use IPVS instead of kube-proxy
3. Drop model front NginX

Next actions:

1) profile request/response chain to figure out latency on each step of chain
2) reduce number of steps in request/response chain according to ideas listed above
3) add performance test into build procedure that will measure request/response time on regular basis for empty/stub ML model which is deployed on ci cluster and has known minimal/zero latency

**Comment by kirillmakhonin** [comment]
Maybe we can use [annotations](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#lua-resty-waf)

**Comment by ablatov** [comment]
@kirillmakhonin, @dsuslov I think that it will take about one day to implement Robot tests for this. The only question is what exactly model should we measure? Test-Summation or the custom one?

**Comment by kirillmakhonin** [comment]
We can remove nginx from model pods. Instead of using uWSGI behind NGINX we can use [native HTTP support in uWSGI](https://uwsgi-docs.readthedocs.io/en/latest/HTTP.html)

**Comment by kirillmakhonin** [comment]
Relevant to #859
