### ISSUE TITLE
Zip Slip vulnerability during unpackaging of a trained artifact

### ISSUE THREAD

**Issue by mcdoker18** [legion-platform/legion#1017]
For example, we should replace the Golang implementation with `zip` CLI.

**Comment by vlad-tokarev** [comment]
Feature already has validation for Zip Vulnerability
`		if !strings.HasPrefix(fpath, filepath.Clean(dest)+string(os.PathSeparator)) {
			return fmt.Errorf("%s: illegal file path", fpath)
		}`
