### ISSUE TITLE
Slack notifications on Airflow DAGs failure

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#156]
On Airflow DAG failure notifications should be sent via Slack. It requires:
1. Python function/module for slack notifications
2. Define separate ETL python package
3. Install ETL python package in Airflow docker image

**Comment by kirillmakhonin** [comment]
@aliaksandr-d what is the status of this issue?

**Comment by aliaksandr-d** [comment]
Merged in #160
