### ISSUE TITLE
Migrate service discovery to Kubernetes native mechanism

### ISSUE THREAD

**Issue by akharlamov** [legion-platform/legion#18]
At the moment Consul is used as a service discovery tool in additional to Etcd used by k8s. It is going to be challenging to maintain both in HA setting.

We need to rewrite edge ingress in order to use etcd as a configuration source.

**Comment by akharlamov** [comment]
Suggested solution: 

Deploy K8S Service object to group model pods and expose them through a cluster IP. Run a separate small container to watch API object changes and regenerate Nginx configuration if needed. 

Run the python watcher in a separate container based on alpine if possible.

**Comment by kirillmakhonin** [comment]
Now we have problem: consul doesn't remove invalid model pods, so we should speed up that issue.
@akharlamov @aliaksandr-d

**Comment by kirillmakhonin** [comment]
Closing this issue would update #25
