### ISSUE TITLE
legionctl undeploy by model version stucks while executing

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#208]
Steps to reproduce:
1. Deploy two models with the same id but different versions.
2. Execute legionctl undeploy by model version from model 1

Expected:
1. Deployment successful for both models
2. Undeploy ends successfully

Actual:
1. ok
2. undeploy command stucks until force kill

Need to add function not to wait (flag) and to make console output of execution.

**Comment by akharlamov** [comment]
We need to identify the reason why undeploy stucks. It might be due the fact the model is never undeployed...

**Comment by ablatov** [comment]
fixed
