### ISSUE TITLE
Command "legionctl deploy image --scale 0" creates 1 instance of the model

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#212]
**Steps to reproduce**
1. Run "legionctl deploy image --scale 0" command
2. Run inspect command for the image from step 1

**Expected:**
1. run successfully without errors
2. inspect command returns nothing (model not deployed)

**Actual:**
1. run successfully without errors
2. inspect command returns info that image was deployed successfully

**Comment by kirillmakhonin** [comment]
@ablatov I've fixed this in branch [feat/212-check-scale-value](/legion-platform/legion/tree/feat/212-check-scale-value). Could you please add tests for this in this branch?

**Comment by ablatov** [comment]
@kirillmakhonin checked on cluster.
**Check steps:**
1. Create new cluster.
2. Build legion from branch  feat/212-check-scale-value. 
3. Deploy legion to the cluster.
4. Run command deploy model with scale == 0.
5. Run scale to 0 command for deployed model.

**Expected result:**
1. Created successfully.
2. Legion was built successfully.
3. Deploy successful.
4. Exception message was received in stderr: "Invalid scale parameter: should be greater then 0". Model was not deployed.
5. Exception message was received in stderr: "Invalid scale parameter: should be greater then 0". Model was not scaled.

**Actual result:**
1. Created successfully.
2. Legion was built successfully.
3. Deploy successful.
4. Model was deployed. No error message.
5. OK

**Comment by ablatov** [comment]
fixed, tests passed
