### ISSUE TITLE
dex chart status check is not correct

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#217]
Ansible task "name: Get Dex chart status" registers helm_dex_status in order to check if dex shuld be installed or not. But in fact we try to install the chart despite of that status and create cluster fails on second run at existing cluster. This makes difficulties in dev work and debugging. We should properly configure helm chart status check so the playbook doesn't get failed in case of existing chart.

**Comment by kirillmakhonin** [comment]
@alexander-semenets this issue should be closed, is not it?

**Comment by alexander-semenets** [comment]
done
