### ISSUE TITLE
Profile&secrets validation prior Legion deployment

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#235]
Currently there is no Profile and Secret validation. And only after Legion deployment we can understand that some property is absent or invalid.
The idea is:
1. create Profile and Secret "schema" files, that define these files format and structure
2. implement validation against  this schema
3. on any new properties creation/modification developer also should update schema in one commit/pull request.

**Comment by alexander-semenets** [comment]
done
