### ISSUE TITLE
Configure Airflow connections with ConfigMap

### ISSUE THREAD

**Issue by dnskr** [legion-platform/legion#253]
Add ConfigMap for storing airflow connections.
Provide mechanism for ConfigMap usage in hooks.

**Comment by akharlamov** [comment]
I do not think this is right approach. I suggest to just use available configmaps as parameters to S3Hooks.

**Comment by kirillmakhonin** [comment]
What is the status of this issue? @aliaksandr-d

**Comment by aliaksandr-d** [comment]
Fixed. Merged
