### ISSUE TITLE
Automatic container changes capture

### ISSUE THREAD

**Issue by akharlamov** [legion-platform/legion#31]
We need a capability to automatically capture changes introduced by pymodel training script into a model image. 

At the moment both model training scripts and HTTP server run inside a clean container built from base image. It has two disadvantages:
- Every time a new ML library or just another python package is needed by model, the base docker image must be released. That is time consuming and not viable for a prod environment. 
- If model can not create produce some intermediate data/files to be used inside serving environment.

**Comment by kirillmakhonin** [comment]
@akharlamov 
But what we would store in model binary? Instructions, performed during train process? Or we should merge export and build step?

**Comment by kirillmakhonin** [comment]
Currently python docker library incorrectly creates docker containers: you cannot setup only binds, you have to setup volumes. But passing volume raises an error after running committed image. Error in docker/models/containers/_create_container_args

**Comment by kirillmakhonin** [comment]
Problem has been solved with selecting `mounts` instead of `volumes`
