### ISSUE TITLE
Disallow scheduling legion components on master nodes

### ISSUE THREAD

**Issue by MaksymBilenko** [legion-platform/legion#310]
Security issue that pods scheduled on masters have R/W access to AWS api.
Required to prepare some disallow rule for scheduling pods on masters (Jenkinsfile, airflow, etc)

**Comment by MaksymBilenko** [comment]
Idea is to disallow all RBAC rules to define `NodeSelector`

**Comment by akharlamov** [comment]
AFAIK, you can taint kubernetes master nodes, so they are not going to be used for general purpose pods. See for details https://www.ibm.com/support/knowledgecenter/en/SSCKRH_1.0.1/platform/install_pod_scheduling.html

**Comment by kirillmakhonin** [comment]
@alexander-semenets please check

**Comment by kirillmakhonin** [comment]
Taints are set up, nobody cant schedule pod manually.
