### ISSUE TITLE
Implement SSO provider that supports 'groups' scope

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#319]
Need to implement an SSO provider that can be integrated with Dex and supports 'groups' scope.
Options:
1. Use OpenID provider, connect it with Dex using OIDC connector, extend current OIDC implementation to pass 'groups' scope
https://github.com/coreos/dex/blob/master/connector/oidc/oidc.go
2. Implement SAML provider and connect to Dex using connector, that supports 'groups' scope by default.
https://github.com/coreos/dex/tree/master/connector/saml

**Comment by dsuslov** [comment]
obsolete due to migration to keycloak
