### ISSUE TITLE
Add auth\security test for legion components

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#323]
Every component must have its own authorization with credentials.
Need to add tests that check all components for:
- valid auth
- invalid auth
- auth presence

**Comment by ablatov** [comment]
@kirillmakhonin @MaksymBilenko I see only jenkins,airflow and K8s dasboard are closed with auth now. Are any other components should be?

**Comment by kirillmakhonin** [comment]
@ablatov all components (exclude model API on EDGE) should be closed with auth
