### ISSUE TITLE
LegionCtl should return legion.k8s.ModelDeploymentDescription for deploy/scale/undeploy commands

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#331]
legionctl command line tool deploy/scale/undeploy/inspect commands returns no output now.
This makes problems for controlling successful executions of these commands.
legion.k8s.ModelDeploymentDescription contains all needed info for such control:
('status', str),
('model', str),
('version', str),
('image', str),
('scale', int),
('ready_replicas', int),
('namespace', str),
('model_api_ok', bool),
('model_api_info', dict)

The expected flow should be:
legionctl command -> EDI -> k8s -> pods(servises) -> k8s -> EDI -> legionctl command stdout containing legion.k8s.ModelDeploymentDescription info in JSON format.

This would help to be sure that legionctl command was fully executed and that there is no needs to set up any sleeps.

**Comment by kirillmakhonin** [comment]
Closed by #354
