### ISSUE TITLE
DAG deploying through EDI

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#36]
In order to deploy Airflow DAGS from cluster-wide Jenkins we need to add to EDI an opportunity to deploy DAGs.

Depends on #347

**Comment by aliaksandr-d** [comment]
Currently we have EDI per Enclave and Airflow server per cluster. We should create Airflow per enclave, to be able to start working on this ticket.

**Comment by kirillmakhonin** [comment]
Should be moved to another repo

**Comment by dsuslov** [comment]
obsolete
