### ISSUE TITLE
Add logs grabber for k8s instances for catching them after test failed

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#377]
**Problem:** 
Now if some test with models fails we do not have enough information about why that exactly happens.
This investigation needs a lot of time to spend on.
**Possible solution:**
Add the keyword to all tests with models 'Run Keyword If test Failed' in which we will take all the logs from  EDI and EDGE.
**Profit**
Make error investigation and fixing faster

**Comment by ablatov** [comment]
@akharlamov, @dsuslov, @kirillmakhonin what do you think of it? Are we going to make this?

**Comment by kirillmakhonin** [comment]
I think it would be nice if we started to catch all logs through kubectl describe, kubectl logs after each (even not failed) deploy with saving as artifacts of Legion Deploy job

**Comment by kirillmakhonin** [comment]
And this action, I guess, should be taken not in Robot Framework but in Jenkins pipeline

**Comment by kirillmakhonin** [comment]
Not needed anymore because after #555 we have logs for each cluster
