### ISSUE TITLE
Failed to work with stored from train step paths

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#406]
If model builds absolute paths they can be stored on serialization. Then when model start it will try to use old (invalid) paths. 
Possible solution: make symlink from work directories to target directories in docker image build

**Comment by akharlamov** [comment]
Could you provide a detailed description of a situation that is happening? That seems like a broken build process to me which should be fixed instead of bunching up symlinks.

**Comment by kirillmakhonin** [comment]
@akharlamov 
Let's look on build&train process:
1. Jenkins starts new slave in new pod
2. Train script executes in WORKSPACE
3. During execution on train script, it can capture absolute paths to datasets (what Victor's model do) and on top of that dill serializes models variables with `__file__` too.
4. Legion builds model: it copies binary model and all files from workdir to `/app` and commits images. Old workdir works as mounted dir and it will not be available after commit.
**5. [NEW] During execution of docker container commit Legion creates symlink from old workdir to new `/app`**

**Comment by akharlamov** [comment]
This begs a question, why do we need to move anything? Can we put it into the same directory inside a container?
