### ISSUE TITLE
Rate exceeded on AWS API calls

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#445]
Sometimes job "Create cluster fails" due to timeouts.
```
ASK [aws_resources : Create Airflow Postgres RDS instance] ********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Timeout waiting for RDS resource legion-ci-airflow-rds"}
	to retry, use: --limit @/var/lib/jenkins/workspace/Create_cluster/deploy/ansible/create-cluster.retry
```

**Comment by alexander-semenets** [comment]
We have Cluster autoscaler pods which trigger AWS API with ASG describe calls and they are eating API calls limits. We can see Rate exceeds errors constantly appearing in autoscaler pod log.

We should decrease API request frequency.
This could also be related to #511
