### ISSUE TITLE
Cleanup call of dex client in legionPipeline

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#455]
This code should be cleaned up (deploy/legionPipeline.groovy)
```groovy
def output = sh(script:'''
....
echo ----
./jenkins_dex_client
''', returnStdout: true)
creds = output.split('----')[1].split('\n')
```

**Comment by aliaksandr-d** [comment]
It fails, because **jenkins_dex_client** is not able to read jenkins Api Token. This field is empty on user configuration page. I guess it's affected by #427

**Comment by aliaksandr-d** [comment]
@kirillmakhonin Jenkins has been recently updated:
https://jenkins.io/changelog-stable/#v2.138.1
And API Token logic has been changed, same as UI:
_Replace single per-user API token with new system of multiple, revocable, unrecoverable API tokens with usage tracking._
