### ISSUE TITLE
Provide a convenient way to install ML model dependencies

### ISSUE THREAD

**Issue by torquerrr** [legion-platform/legion#468]
Instead of using custom built images for ML models it would be better to install all required dependencies directly, using _requirements.txt_ file.
In order for this to work I suggest modifying _legion.groovy_ script like this:
`def runScript(scriptPath, use_dependencies = false){
    env.ROOT_DIR = rootDir()
    env.TARGET_SCRIPT_PATH = scriptPath
    env.MODEL_ID = defaultModelId(scriptPath)

    echo 'ROOT_DIR = ' + env.ROOT_DIR
    echo 'TARGET_SCRIPT_PATH = ' + env.TARGET_SCRIPT_PATH
    echo 'MODEL_ID = ' + env.MODEL_ID

    sh """
    pip3 install --extra-index-url \$LEGION_PACKAGE_REPOSITORY legion==\$LEGION_PACKAGE_VERSION
    export CONTAINER_DIR="`pwd`"
    cd ${env.ROOT_DIR}
    if ( use_dependencies )
    {
        pip3 install -r requirements.txt
    }
    python3.6 "${env.TARGET_SCRIPT_PATH}" | tee script-log.txt`

**Comment by akharlamov** [comment]
Legion provides such capabilities already through invocation of install commands in the training script. No change required.
