### ISSUE TITLE
Move installation of all dependencies to EDGE dockerfile

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#469]

**Comment by akharlamov** [comment]
Could you provide more background context on the matter? What does the ticket stands for?

**Comment by kirillmakhonin** [comment]
We need this modification to speed up CI cycle (#375). `legion-template` tool is used in EDGE image to substitute information about model services to NGINX configuration. So, `legion-template` is distributed in package `legion`, which requires lots of ML dependencies (pandas and etc.). To speed up each build we can put installation of requirements outside of installation of fresh legion version. In this case Docker engine will cache dependencies
