### ISSUE TITLE
Automate Nexus setup and configuration for CI infrastructure in GCP

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#491]
This is subtask of #558

1) Automate provisioning separate VM for Nexus
2) Follow best practices for VM configuration like 1) use different disk volumes for root FS and FS for storing big data volumes 2) use I/O optimised disk volumes 3) configure firewall rules to disable access outside, etc   
3) Nexus has to be deployed in Docker container
4) Automate configuration of Nexus repositories as much as possible
5) Use separate blobs for separate Nexus repositories
6) Use proxies for 3d party repositories and repo groups to expose the read access for docker and other types of repos via minimal number of endpoints
7) Configure auth via github identity. Do not save credentials in configuration files and disable default user 
8) Configure regular backup of Nexus configuration and repositories

**Comment by karbyshevds** [comment]
Implemented terraform scripts that:
- Creates GCP VM to run Nexus in private network
- Creates GCP VM to run Nginx proxy with public IP address
- Generates Let's encrypt certificates for Nexus
Implemented Dockerfile to build Nexus image
Implemented Nexus configuration scripts that configures repositories except helm

https://git.epam.com/epmd-legn/legion-cicd/tree/feat/558

ToDo:
- Find a way to automate helm repo creation
- Use separate blobs for separate Nexus repositories
- Configure auth via github identity. Do not save credentials in configuration files and disable default user
- Configure regular backup of Nexus configuration and repositories

**Comment by alexander-semenets** [comment]
done
