### ISSUE TITLE
Automate Jenkins setup and configuration for CI infrastructure in GCP 

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#492]
This is subtask of #558

1. Automate provisioning separate VM for Jenkins Master
2. Follow best practices for VM configuration like 1) use different disk volumes for root FS and FS for storing service configuration data 2) use I/O optimised disk volumes 3) configure firewall rules to disable access outside, etc
3. Jenkins master has to be deployed in Docker container
4. Jenkins slaves has to be in Docker containers
5. Configure slave VMs provisioning on-demand and stop or termination after defined period of non-use period  
6. Automate configuration of Jenkins as much as possible
7. Configure auth via github identity. Do not save credentials in configuration files and disable default user
8. Configure regular backup of Jenkins master configuration or VM instance

**Comment by karbyshevds** [comment]
Implemented terraform scripts that:
- creates GCP VM to run Jenkins in private network
- creates GCP VM to run Nginx proxy with public IP address
- Generates Let's encrypt certificates for Jenkins

Implemented Dockerfile to build Jenkins image
Implemented Packer configuration to build Jenkins slave image on GCP

Current logic:
- VM checks if attached disk is empty on startup
- If attached disk is empty, latest backup is downloading and extracting
- Docker container is launching

https://git.epam.com/epmd-legn/legion-cicd/tree/feat/558

**Comment by alexander-semenets** [comment]
done
