### ISSUE TITLE
Update documentation about CLI tools: legionctl, edi, web console, legion-test tools and etc.

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#51]

**Comment by aliaksandr-d** [comment]
I found **legionctl**.
What does **EDI CLI tool** mean? EDI server?
Same question regarding **legion-test**

**Comment by kirillmakhonin** [comment]
It means any tools than can be used directly: EDI server an so on

ср, 2 мая 2018 г., 13:39 Alexander D <notifications@github.com>:

**Comment by dsuslov** [comment]
obsolete
