### ISSUE TITLE
Cluster autoscaler doesn scale down temp r4.large node after PERF TEST Vertical-Scaling

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#511]
The node should be scaled down as soon as test passed, by the way it remains and Cluster Autoscaler doesn't tear it down.

`$kubectl get nodes
NAME                                           STATUS    ROLES     AGE       VERSION
ip-172-31-100-192.us-east-2.compute.internal   Ready     master    3h        v1.9.3
ip-172-31-103-241.us-east-2.compute.internal   Ready     node      3h        v1.9.3
ip-172-31-104-189.us-east-2.compute.internal   Ready     node      3h        v1.9.3
ip-172-31-105-36.us-east-2.compute.internal    Ready     node      1h        v1.9.3
ip-172-31-105-44.us-east-2.compute.internal    Ready     node      3h        v1.9.3`

**Comment by ablatov** [comment]
fixed in #522
