### ISSUE TITLE
Split Legion integration tests  on 2 groups: infrastructure and applications

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#516]
All tags in robot integration tests  have to reviewed to split integration tests on 2 groups infrastructure (infra )and applications (apps) tests. Infra tag will be used for infrastructure CI jobs and apps tag will be used for applications CI jobs. For full CI cycle both tags (infra and apps) have to be used.

**Comment by ablatov** [comment]
Done in #519
