### ISSUE TITLE
Need an option to remove and invalidate API token

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#525]
Currently EDI server generates JWT tokens based on Secret and Expiration date. Tokens are valid till expiration date. Need to implement a feature to invalidate existing token.

One of the possible solution is:

    Store blacklisted tokens flat in the ConfigMap (one per line)
    Mount blacklisted tokens on EDGEs
    Read blacklisted tokens on start and keep in in memory using Lua
    Monitor them using legion-template tool and reload nginx on each config-map update (as we doing now for statistics)
    On file update blacklist will be reloaded in-memory.
    Request filtering will be done by lua scripts (checking token existence in in-memory array)

**Comment by aliaksandr-d** [comment]
An idea is that we can change existing secret on fly. What do you think about it?
@dsuslov @akharlamov

**Comment by aliaksandr-d** [comment]
@kirillmakhonin proposed next solution:
```
One of the possible solution is:

    Store blacklisted tokens flat in the ConfigMap (one per line)
    Mount blacklisted tokens on EDGEs
    Read blacklisted tokens on start and keep in in memory using Lua
    Monitor them using legion-template tool and reload nginx on each config-map update (as we doing now for statistics)
    On update file will be re-readed
    Request filtering will be done by lua scripts (checking token existence in in-memory array)
```

**Comment by leshchanka-aliaksandr** [comment]
We have tried to use ionotify but it doesn't work for any files in k8s (docker). Now we are trying to use k8s  api  watch function
