### ISSUE TITLE
Add enclave inspection in legionctl

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#53]
Legionctl tool should contain command to get list of enclaves.

**Comment by kirillmakhonin** [comment]
Also we can add `--cluster` instead of  `--edi` and `env:EDI_URL` configurations to simplify configuration of `legionctl`.

**Comment by aliaksandr-d** [comment]
As far as i understand, it needs Liara to get a list of enclaves. Am i right?
