### ISSUE TITLE
Extend EDI API with methods for ML model training pipeline lifecycle

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#540]
The list of required API methods for ML model training lifecycle:
 
'/api/{version}/training/projects'  # HTTP POST - import ML model project
'/api/{version}/training/projects'  # HTTP GET - list ML model training pipeline projects in enclave 
'/api/{version}/training/projects/{project_name}'  # HTTP DELETE - delete ML model training project from enclave
'/api/{version}/training/projects/{project_name}/executions'  # HTTP POST - execute ML model training pipeline
'/api/{version}/training/projects/{project_name}/executions'  # HTTP GET - get list of training pipeline executions history
'/api/{version}/training/projects/{project_name}/executions/{execution_id}/cancel'  # HTTP POST -cancel training pipeline execution
'/api/{version}/training/projects/{project_name}/executions/{execution_id}'  # HTTP GET - get status of training pipeline execution 
'/api/{version}/training/projects/{project_name}/executions/{execution_id}/logs'  # HTTP GET - get logs of training pipeline execution

AS a first step please, add these methods into EDI API without actual implementation. The implementation of each method should be done as a separate tasks.

**Comment by akharlamov** [comment]
This functionality is very specific for a company and an implementation. I do not think it needs to be part of the legion core. If people needs to have it, there is Jenkins API readily available. 

Please, stop work on this immediately.

**Comment by dsuslov** [comment]
@akharlamov, the API extension was discussed and we had reached agreement from all interested parties. The result of those discussion was documented in google groups. Look at https://groups.google.com/forum/#!topic/legion-dev/251iLGwYdZg - **Section 2)**. 

If you have changed your vision recently please communicate this new vision to all all interested parties.
