### ISSUE TITLE
Add possibility to blacklist model API tokens

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#548]

**Comment by kirillmakhonin** [comment]
One of the possible solution is:
1. Store blacklisted tokens flat in the ConfigMap (one per line)
2. Mount tokens on EDGEs
3. Read tokens on start and keep in in memory using Lua
4. Monitor them using `legion-template` tool and reload on each config-map update
5. On update file will be re-readed
6. Request filtering will be done by lua scripts (checking token existence in in-memory array)

**Comment by aliaksandr-d** [comment]
Closing this issue as duplicate of #525

**Comment by teamnorge** [comment]
One of the requirements we have is to have "per model" tokens as well. Any ideas on how to implement it as well as blacklisting "per model" tokens.
