### ISSUE TITLE
Create CI build pipeline for cluster infrastructure components to produce set of deliverable infrastructure units 

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#566]
Create Jenkins build pipeline for cluster infrastructure components. 
This pipeline should include:
1) build of 3d party customised docker containers.
     - move infra related dockerfiles (kube-fluentd, elb-security, ?) to k8s/k8s-infra
     - create jenkins job for Infra images build
     - update release pipeline with new step for infra 
     - update playbooks\charts\etc with new images location
     - update existing jenkins jobs with new infra version tag parameter
     - include dex build into this build pipeline. We customised dex in https://github.com/legion-platform/dex/commits/feat/oidc-groups. Rename branch  oidc-groups - > legion and set legion release tag.
2) package helm charts (to be discussed )
     - public repo for releases https://github.com/helm/charts
     - private repo for snapshots https://github.com/sonatype-nexus-community/nexus-repository-helm 
3) package ansible scripts docker image
     - public repo for releases docker hub
     - private repo for snapshots nexus

Single version of Legion infrastructure should be set for all packages and containers listed above. Packages and container should be published to repositories (Nexus or public repos - to be discussed)

Create cluster pipeline should depend on these containers and packages but not on Legion git repository.

**Comment by alexander-semenets** [comment]
Brief step list:
- move infra related dockerfiles (kube-fluentd, elb-security, ?) to k8s/k8s-infra
- create jenkins job for Infra images build
- update release pipeline with new step for infra 
- update playbooks\charts\etc with new images location
- update existing jenkins jobs with new infra version tag parameter
