### ISSUE TITLE
Potential security vulnerabilities with "requests" Python package

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#569]
Fix potential security vulnerabilities in dependencies reported by github https://github.com/legion-platform/legion/network/alerts

Upgrade **requests** to version 2.20.0 or later. 
Vulnerable versions: <= 2.19.1
Patched version: 2.20.0

The Requests package through 2.19.1 before 2018-09-14 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.

**Comment by kirillmakhonin** [comment]
Closed by #618
