### ISSUE TITLE
Small Jenkins cannot find sources for Jobs in repo

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#597]
Maybe there is a problem with GC on GitHub side, because result (commit) of merging (PR to develop) is not tagged or marked as a branch.

**Comment by mcdoker18** [comment]
I guess that the issue was resolved by https://github.com/legion-platform/legion/pull/751
@kirillmakhonin @alexander-semenets  Please, reopen if i am wrong.
