### ISSUE TITLE
Posibility to define Jenkins jobs using DSL scripts

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#609]
Currently Jenkins jobs are imported using create_example_jobs utility. Job-DSL is another approach the helps to construct Jenkins job in more flexible way.
```The job-dsl-plugin allows the programmatic creation of projects using a DSL. Pushing job creation into a script allows you to automate and standardize your Jenkins installation, unlike anything possible before.```
https://wiki.jenkins.io/display/JENKINS/Job+DSL+Plugin

**Comment by dsuslov** [comment]
"Small" Jenkins will be removed from Legion cluster see #616
