### ISSUE TITLE
Make Legion neutral to particular Docker repository

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#617]
This is subtask of #938

Legion platform has to be neutral to Docker repository and does not stick to particular repository like Nexus. So, to make it possible the following tasks should be completed:

1. refactor code to make docker repository for ML models fully configurable
2. add CR and operator for managing Docker Registry credentials 
3. add possibility to pass name for result images
4. add commit id & rand() to name for default generated image names

**Comment by kirillmakhonin** [comment]
Awaiting #924
