### ISSUE TITLE
Handle legion documentation during release

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#668]
During the build procedure we generate documentation and store it at Jenkins filesystem. The documentation is not rotated and not published anywhere like other artifacts do.
We should think of generating artifact with documentation during stable releases and publish it to some storage.

**Comment by mcdoker18** [comment]
Implemented by @kirillmakhonin  in https://github.com/legion-platform/legion/commit/50793a731d334aab5ee89d6cafc7eebdb02b5099
