### ISSUE TITLE
Fix pylint warnings

### ISSUE THREAD

**Issue by mcdoker18** [legion-platform/legion#686]
We observe more 1100 pylint warnings after fixing of linter in the #665  PR. 
Warnings: https://cc.epm.kharlamov.biz/jenkins/job/Build_Legion_Artifacts/
Need to fix them.

**Comment by skayerok** [comment]
It seems that our `.pylintrc` doesn't work, because I can see a lot of warning about line length exceeding 100 symbols though in `.pylintrc` it is set to 120 symbols.
If we fix it, some amount of warnings should go away. And after that we need to fix the rest.
