### ISSUE TITLE
Refactoring of Legion platform code structure 

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#690]
Code structure has to be refactored in accordance with following approach:

[ROOT] - each 1st level is directory (package), 2nd+ levels are modules
    ├── utils (template engine, text/formatting utils)
    ├── platform
    |   ├── core: All entities of legion-platform (model, enclave, storage, etc ) - depends on .utils
    |   ├── services (EDI server and etc.) - depends on .platform-core
    |   ├── client (EDI client, Grafana client and etc.) - depends on .platform-core
    ├── python-toolchain
    ├── spark-toolchain
    ├── tf-toolchain

The structure of testing code has to be refactored too. New structure - TBD.

**Comment by kirillmakhonin** [comment]
We are proposing new structure of Python packages:

1. Core
2. Services (EDI server) - depends on Core
3. CLI (legionctl) - depends on Core
4. Toolchains 
4.1. Python Toolchain - depends on Core

**Comment by kirillmakhonin** [comment]
There is proposed structure of Leigon python packages (every rectangle is a distribution package)
<img width="1176" alt="screen shot 2019-02-05 at 1 50 32 pm" src="https://user-images.githubusercontent.com/3201565/52268644-1b5fe200-294d-11e9-8c3e-b0fbbebbce9c.png">

**Comment by kirillmakhonin** [comment]
PyPi structure:

- legion - legion-core
- legion[cli] - legion-cli
- legion[services] - legion-services
- legion[testing] - legion-testing
