### ISSUE TITLE
Get rid of Graphite in Legion enclave

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#711]
Currently Legion contains 2 different tools for serving different metrics - Prometheus and Graphite. To reduce number of tools which serve metrics and to use single tech. stack for this purpose Graphite can be replaced with https://github.com/prometheus/pushgateway + Prometheus for metrics which can only be pushed but not pulled.

**Comment by alexander-semenets** [comment]
https://github.com/cherti/PromAuthProxy this might be used to restrict access from tenant to core space prometheus metrics
