### ISSUE TITLE
Add model token generation command for legionctl

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#712]
We have to add CLI command for `legionctl` to generate model API JWT access tokens.

**Comment by mcdoker18** [comment]
Need to:
1) Add new command to the `legionctl`
2) Create new robot tests
3) Replace `generate_token` raw http query by `legionctl` in robot tests
4) Update `legionctl` docs

**Comment by skayerok** [comment]
This issue can be closed
