### ISSUE TITLE
Stabilize CI builds

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#714]
The most of nightly CI builds several last weeks are failed due to various reasons related to infrastructure automation code and application code.

@alexander-semenets please look at last failed nightly builds and fix issues related to infrastructure automation code. For instance look at these failed steps from last nightly CI:
- https://cc.epm.kharlamov.biz/jenkins/job/Terminate_cluster/3182/execution/node/39/log/
- https://cc.epm.kharlamov.biz/jenkins/job/Build_Legion_Artifacts/196/execution/node/268/log/ 

@mcdoker18 and @kirillmakhonin  please look at last failed nightly builds and fix issues related to application code.

**Comment by dsuslov** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/179/robot/report/log.html#s1-s7-t6

TEST CASE:	Check EDI scale down 1 of 2 models with different versions but the same id
Tags:	apps, cli, edi, enclave, multi_versions
Duration:	0:01:51.141 (+0:00:45.550)
Status:	FAIL (critical)
Message:	Teardown failed:
Several failures occurred:

1) 2 != 0

2) 'Model ID           |Image                                                                                                     |Version |Ready |Scale |Errors                            
command-test-model |nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-5:0.10.0-20190103010626.201.ff62112 |1.0     |1     |1     |                                  
demo-abc-model     |nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-2:0.10.0-20190103010626.201.ff62112 |1.1     |1     |1     |                                  
edi-test-model     |nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-3:0.10.0-20190103010626.201.ff62112 |1.2     |1     |1     |                                  
recognize-digits   |localhost:31111/legion_model/recognize-digits:1.0-190103015905.1.ff62112                                  |1.0     |0     |1     |ERROR: MODEL API DOES NOT RESPOND 
test-summation     |localhost:31111/legion_model/test-summation:1.0-190103015424.1.ff62112                                    |1.0     |1     |1     |                                  ' contains 'nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-2:0.10.0-20190103010626.201.ff62112'

**Comment by dsuslov** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/175/robot/report/log.html#s1-s3-t1


Full Name: | Suites.1.2 Check Airflow.Check test dags should not fail
-- | --
Connect to Airflow and check the status of test dags are not failed
airflow, airflow-api, apps
20190102 04:54:15.037 / 20190102 04:54:27.114 / 00:00:12.077
FAIL (critical)
'[]' should not be empty.

**Comment by dsuslov** [comment]
https://jenkins.cc.epm.kharlamov.biz/jenkins/job/Build_Legion_Artifacts/202/testReport/junit/test_metrics/TestMetrics/test_metrics_send/

test_metrics.TestMetrics.test_metrics_send (from nosetests)

Error Message
'1546500955' != '1546500954'
- 1546500955
?          ^
+ 1546500954
?          ^
Stacktrace
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "/src/legion/tests/test_metrics.py", line 75, in test_metrics_send
    self.assertEqual(call_with_build_number[2], str(timestamp))
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 836, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 1215, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 690, in fail
    raise self.failureException(msg)
AssertionError: '1546500955' != '1546500954'
- 1546500955
?          ^
+ 1546500954
?          ^

**Comment by alexander-semenets** [comment]
test_metrics.TestMetrics.test_metrics_send (from nosetests) 
Stacktrace

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "/src/legion/tests/test_metrics.py", line 75, in test_metrics_send
    self.assertEqual(call_with_build_number[2], str(timestamp))
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 836, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 1215, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 690, in fail
    raise self.failureException(msg)
AssertionError: '1547256014' != '1547256013'
- 1547256014
?          ^
+ 1547256013
?          ^

**Comment by mcdoker18** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/188/robot/report/log.html#s1-s6-t6-k2-k3
stderr = 2019-01-09 09:23:36,449 - INFO - Sending deploy request to EdiClient('https://edi-company-a.legion-dev.epm.kharlamov.biz') 2019-01-09 09:23:36,450 - DEBUG - Requesting https://edi-company-a.legion-dev.epm.kharlamov.biz/api/1.0/deploy 2019-01-09 09:23:36,453 - DEBUG - Starting new HTTPS connection (1): edi-company-a.legion-dev.epm.kharlamov.biz:443 2019-01-09 09:23:46,184 - DEBUG - https://edi-company-a.legion-dev.epm.kharlamov.biz:443 "POST /api/1.0/deploy HTTP/1.1" 500 170 2019-01-09 09:23:46,186 - DEBUG - Got response. Breaking 2019-01-09 09:23:46,186 - DEBUG - Got answer: {'error': True, 'exception': 'Cannot find deployment for model service <bound method ModelService.__str__ of ModelService for model auth-test-model version 1.0>'} with code 500 for URL 'https://edi-company-a.legion-dev.epm.kharlamov.biz/api/1.0/deploy' 2019-01-09 09:23:46,186 - ERROR - Got error from server: 'Cannot find deployment for model service <bound method ModelService.__str__ of ModelService for model auth-test-model version 1.0>' Traceback (most recent call last):   File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/bin/legionctl", line 170, in <module>     args.func(args)   File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/edi/deploy.py", line 296, in deploy_kubernetes     args.readinesstimeout)   File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/external/edi.py", line 203, in deploy     return self.parse_deployments(self._query(legion.edi.server.EDI_DEPLOY, action='POST', payload=payload))   File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/external/edi.py", line 131, in _query     raise Exception('Got error from server: {!r}'.format(exception)) Exception: Got error from server: 'Cannot find deployment for model service <bound method ModelService.__str__ of ModelService for model auth-test-model version 1.0>
--

**Comment by mcdoker18** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/225/testReport/junit/test_k8s_model_operations/TestK8SModelOperations/test_model_scale_up_and_down/
```
test_k8s_model_operations.TestK8SModelOperations.test_model_scale_up_and_down (from nosetests) 

0 != 1 : desired and current scales are not equal
```

**Comment by mcdoker18** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Build_Legion_Artifacts/302/testReport/junit/test_utils_external_file/TestUtilsExternalFile/test_external_file_reader_https_example/

```
Сообщение об ошибке
Cannot load resource: https://example.com/index.html. Returned status code: 502
Стек вызовов
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/site-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "/src/legion/tests/test_utils_external_file.py", line 120, in test_external_file_reader_https_example
    with utils.ExternalFileReader(resource) as reader:
  File "/src/legion/legion/utils.py", line 467, in __enter__
    self._download()
  File "/src/legion/legion/utils.py", line 457, in _download
    self._local_path = download_file(self._path)
  File "/src/legion/legion/utils.py", line 390, in download_file
    raise Exception('Cannot load resource: %s. Returned status code: %d' % (url, response.status_code))
Exception: Cannot load resource: https://example.com/index.html. Returned status code: 502
```

**Comment by dsuslov** [comment]
Documentation:
Check that requests count metric for model exists
Start / End / Elapsed:
20190117 21:02:18.820 / 20190117 21:02:18.867 / 00:00:00.047
21:02:18.866
INFO
Loading highestMax(stats.legion.model.test-summation.1-0.default.request.count, 1) metrics. Data: [{"target": "stats.legion.model.test-summation.1-0.default.request.count", "datapoints": [[0.0, 1547776640], [0.0, 1547776650], [0.0, 1547776660], [0.0, 1547776670], [0.0, 1547776680], [0.0, 1547776690], [0.0, 1547776700], [0.0, 1547776710], [0.0, 1547776720], [0.0, 1547776730], [0.0, 1547776740], [0.0, 1547776750], [0.0, 1547776760], [0.0, 1547776770], [0.0, 1547776780], [0.0, 1547776790], [0.0, 1547776800], [0.0, 1547776810], [0.0, 1547776820], [0.0, 1547776830], [0.0, 1547776840], [0.0, 1547776850], [0.0, 1547776860], [0.0, 1547776870], [0.0, 1547776880], [0.0, 1547776890], [0.0, 1547776900], [0.0, 1547776910], [0.0, 1547776920], [0.0, 1547776930]]}]

21:02:18.867
FAIL
Cannot find any value > 0

https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/285/robot/report/log.html#s1-s5

**Comment by mcdoker18** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/291/robot/report/log.html#s1-s8-t4
```
Documentation: | Fails if any element in the list is found from it more than once.
-- | --
20190118 19:33:58.895 / 20190118 19:33:58.896 / 00:00:00.001
19:33:58.895 | INFO | 'aa2b8d01-13c2-4cf5-9196-109081258e56' found 2 times. |  
-- | -- | -- | --
19:33:58.895 | INFO | 'aa2b8d01-13c2-4cf5-9196-109081258e56' found 2 times. |  
-- | -- | -- | --
```

**Comment by skayerok** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/302/robot/report/log.html#s1-s7-t8-k1-k1-k3

```
Check EDI scale up 1 of 2 models without version                      | FAIL |
Setup failed:
2 != 0
```

**Comment by skayerok** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Deploy_Legion_Release/379/robot/report/log.html#s1-s8-t4-k6
`Check model API request generation have no duplicates`
```
Fails if any element in the list is found from it more than once.
'34c3babd-930b-4958-824b-ba72d4bc9156' found multiple times.
```

**Comment by mcdoker18** [comment]
https://cc.epm.kharlamov.biz/jenkins/job/Create_cluster/333/console
```
TASK [aws_resources : Create Airflow Postgres RDS instance] ********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Timeout waiting for RDS resource legion-ci-airflow-rds"}
	to retry, use: --limit @/opt/legion/deploy/ansible/create-cluster.retry
```

**Comment by kirillmakhonin** [comment]
@mcdoker18 we've talked about it previously. We will move airflow out from legion repo with this test. Also, maybe, we have to replace RDS with RDMBS inside K8S cluster (for portability).

**Comment by mcdoker18** [comment]
Ticket for network problem is #627

**Comment by mcdoker18** [comment]
Jenkins problem is described here https://github.com/legion-platform/legion/issues/775
All other issues were fixed. Closed.
