### ISSUE TITLE
Update beta kubernetes objects to stable versions

### ISSUE THREAD

**Issue by mcdoker18** [legion-platform/legion#720]
We should upgrade all beta kubernetes object to stable version.
For example:
* model `ExtensionsV1beta1Deployment` to `V1Deployment`
* edi\edge `ReplicationController` to `V1Deployment`
* Role and RoleBinding `rbac.authorization.k8s.io/v1beta1` to `rbac.authorization.k8s.io/v1`

and so on.

**Comment by skayerok** [comment]
eta: Jan, 21
