### ISSUE TITLE
Legion cluster logs rotation in cloud object storage

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#748]
We have to rotate old cluster logs (that are placed on S3 or GCS) on regular basis.

**Comment by kirillmakhonin** [comment]
We have to set-up Lifecycle-Policy for buckets.

**Comment by kirillmakhonin** [comment]
Duration: 1 month

**Comment by mcdoker18** [comment]
Currently, all our buckets are temporary. They are removed during a the Terraform destroy command. If there are no objections, I am closing the ticket. @kirillmakhonin  @dsuslov
