### ISSUE TITLE
Review labels for a model pod

### ISSUE THREAD

**Issue by aliaksandr-d** [legion-platform/legion#76]
Currently each model pod has a number of labels. Several of them are duplicated. They should be reviewed, and spare labels should be removed.

>                 com.epam.legion.class=pyserve
>                 com.epam.legion.container-type=model
>                 com.epam.legion.model.id=test-summation
>                 com.epam.legion.model.version=1.0
>                 com.epam.legion.version=0.5.6-180504101125.252.c5be453
>                 com.epam.model.id=test-summation
>                 com.epam.model.version=1.0

**Comment by aliaksandr-d** [comment]
Services also have inconsistent labels. I saw *legion.component* and *legion/component*

**Comment by kirillmakhonin** [comment]
@aliaksandr-d what is the status of this issue?

**Comment by aliaksandr-d** [comment]
This issue is redundant.
