### ISSUE TITLE
Pin all third-party docker images with sha

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#761]
We have to pin Docker images (third-party) to exact SHA hashes, to rid off fails in case of uncontrolled updating Docker image tags with newer images.
Example: `FROM tensorflow/tensorflow@sha256:5edc0446cc989ad75bc30631f89f20694fe5bf5226f665d47e5c7f35a3b18484`

**Comment by mcdoker18** [comment]
Merged #765
