### ISSUE TITLE
Jenkins model jobs stuck on agent node provisioning

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#775]
`Running on Jenkins in /var/jenkins_home/workspace/DYNAMIC MODEL Test-Summation
[Pipeline] {
[Pipeline] legion
[Pipeline] load
[Pipeline] { (/var/jenkins_home/jobs/DYNAMIC MODEL Test-Summation/builds/1/scripts/legion.groovy)
[Pipeline] }
[Pipeline] // load
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label jenkins-build-bbee6ccd-22de-4f42-b699-71f4070e09ec`

**Comment by kirillmakhonin** [comment]
Not relevant
