### ISSUE TITLE
Install legion from stable and RC releases

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#776]
there is a problem with legion installation from stable artifacts, one of them is dex version which is now not a part of legion release now:
******************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["helm", "--kube-context", "legion-dev.epm.kharlamov.biz", "install", "legion-helm/dex", "--name", "dex", "--version=0.10.0rc10", "--namespace", "kube-system", "-f", "/tmp//dex.legion-dev.epm.kharlamov.biz.yml", "--wait"],

**Comment by mcdoker18** [comment]
@alexander-semenets Version of helm chart must follow semantic versioning specification https://semver.org/#semantic-versioning-specification-semver
