### ISSUE TITLE
Feedback events registration

### ISSUE THREAD

**Issue by akharlamov** [legion-platform/legion#8]
We need to provide a facility to record feedback events (like conversions) and maintain a date partitioned log on S3. 

The facility is not directly related with any model, so we can simply assume to record HTTP calls to api/event/<event_type>?parameters into a json file.

**Comment by kirillmakhonin** [comment]
Fluentd has been added to stack, now I'm waiting for credentials for testing on cluster

**Comment by kirillmakhonin** [comment]
Fluentd has been added, ansible roles has been added, full stack has been tested. Now I'm working on fluentd tests.
