### ISSUE TITLE
Secure access to Legion secrets

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#84]
At the moment secret data are available for read access to any user capable to open Legion services: 
- K8S Secrets available through the dashboard
- S3 credentials are readable from Airflow console
- Jenkins secrets are readable

We need to ensure all the leak sources are secured.

**Comment by MaksymBilenko** [comment]
From cluster side k8s api access restricted on every component (jenkins, airflow, etc)

**Comment by kirillmakhonin** [comment]
@akharlamov what do we want in 3rd point? Jenkins doesn't contains secrets (except GIT key that stores hidden in Jenkins)

**Comment by akharlamov** [comment]
If Jenkins does not contain any sensitive information, for instance AWS credentials, we can ignore it for now.

**Comment by kirillmakhonin** [comment]
We need to move default credentials to secrets and use them @MaksymBilenko

**Comment by MaksymBilenko** [comment]
@kirillmakhonin airflow has default credentials to avoid chart failures with default values.
Real credentials defined on https://github.com/epam/legion/blob/11e8e995f3252d1abd08fdc8cc9ef20f819e8e36/deploy/ansible/site.yml#L36

**Comment by MaksymBilenko** [comment]
As I understand we still going to have auth via DEX, so probably this PR would be cancelled

**Comment by MaksymBilenko** [comment]
Closed in favor of #154
