### ISSUE TITLE
Jupyter notebook for Legion quick start with usage examples

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#888]
As a DS engineer I want to have examples in Jupyter notebook about what I can do with model (deploy, call, undeploy) locally and on a cluster.

Also it would be nice to have Postman collections that are ready-to-use (configurable from variables).

Also this examples should contain feedback invocation.

**Comment by mcdoker18** [comment]
Implemented(swagger for models and feedback)

**Comment by dsuslov** [comment]
examples are here https://github.com/legion-platform/legion-examples
