### ISSUE TITLE
Legion plugin for JupyterLab

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#895]
As a user of local or cloud deployed JupyterLab I want to:

For local mode:
1. Start local build
2. Get locally builded images
3. Deploy & undeploy locally builded images locally
4. Monitor state of local deployments

For cloud mode:
1. Authorize / UnAuthorize on cloud
2. Get cluster trainings
3. Create cluster trainings
4. Create & remove cluster deployments
5. Monitor cluster deployments (name, model, scale)
6. Scale cluster deployments

All mods (local & cloud) should be individually configurable.

**Comment by dsuslov** [comment]
- automatically disconnect plugin from Legion API when session is expired
- rename k8s related action name like "apply resources" to some thing general like "submit ML training job" and "deploy AI service"
- keep only one way to submit ml training job and deploy ai service - via ML training and deployment profiles. Remove actions from interface that allows to submit training and deployment tasks bypassing profiles defined in text files.
