### ISSUE TITLE
Connections API

### ISSUE THREAD

**Issue by mcdoker18** [legion-platform/legion#924]
This is subtask of #938 

As a creator of ML models, I want to have an ability to specify training data on a ModelTraining entity.

We support the following type of data sources in the first step:
* aws s3
* gcp cloud storage
* http api

Also, this resource might be used for managing access to Docker Registries and such kind of resources.

In addition, role based access (e.g. kube2iam should be supported)

**Comment by kirillmakhonin** [comment]
@mcdoker18 , could you please add this to docs branch too?
