### ISSUE TITLE
Pluggable packaging mechanism for trained ML models

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#938]
This is subtask of #929

As a user of Legion platform, I want to have an ability to pack trained models to different "target runtime platform", e.g. K8S, AWS SageMaker, AWS Lambda functions, GCP Cloud functions, UDF for Spark and etc.

Subtasks:
- #934 - Add capabilities to pack Legion model as HTTP RESTful service into Docker image. 
- #617 - Make Legion neutral to particular Docker repository

**Comment by mcdoker18** [comment]
Implemented #988
