### ISSUE TITLE
Airflow operator for Legion ML Training API

### ISSUE THREAD

**Issue by dsuslov** [legion-platform/legion#941]
Legion provides RESTful API to execute ML training job in K8S cluster. So, it would be useful to have custom Legion Airflow operator on top of Legion RESTful API for submitting ML training jobs from Airflow DAGs.

**Comment by jasonnerothin** [comment]
Is this the flow @dsuslov ?
[![image](https://user-images.githubusercontent.com/449078/61826960-276f2b80-ae29-11e9-85bf-6af0b3b1b5d6.png)](url)

**Comment by jasonnerothin** [comment]
Left-most entity executes from within AirflowEngine, as specified in a DAG definition...

![image](https://user-images.githubusercontent.com/449078/61829989-b8490580-ae2f-11e9-9e52-663482b5b738.png)

**Comment by dsuslov** [comment]
@jasonnerothin last diagram is correct :) Note that with such approach Airflow and Legion APIs can be deployed in different K8S clusters or in the same.
