### ISSUE TITLE
Create profile for new demo purposes environment in GCP

### ISSUE THREAD

**Issue by karbyshevds** [legion-platform/legion#945]

**Comment by karbyshevds** [comment]
Created profile, uploaded secrets file
Uploaded SSH key to AWS s3 bucket
updated `Update_TLS_Certificate_GCP` , `GCP_Destroy_cluster`, `GCP_Create_cluster` and `GCP_Deploy_Legion` with new option.

**Comment by alexander-semenets** [comment]
done
