### ISSUE TITLE
Terraform module for TLS certificates update

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#958]
As a DevOps engineer I'd like to have a Jenkins job which triggers terraform scripts for TLS certificates validation and update for all known Legion clusters so I can decommission corresponding Ansible scripts and have valid certificates for each environment.

**Comment by maxkochubey** [comment]
The necessary changes are made in the corresponding branch of the legion-cicd internal repository (`feat/958-letsencrypt-tls`).
Files with Jenkins pipelines are moved to the pipelines directory, similar to the structure in the legion-infrastructure repository.
Jenkins jobs have been created - both for infrastructure and for existing clusters (`TLS_Certificate_Update_958` and `Validate_all_TLS_certificates_958` in Jenkins `Admin` view).

TODO:
- Change Jenkins jobs after branch merge to `develop`
- Remove unused anymore Ansible roles and playbooks from legion-infrastructure `develop` branch

**Comment by alexander-semenets** [comment]
done
