### ISSUE TITLE
Create Jenkins Job for GCP clusters daily cleanup

### ISSUE THREAD

**Issue by alexander-semenets** [legion-platform/legion#967]
As a DevOps engineer I'd like to have jenkins job which removes all legion dev clusters at GCP so all abandoned clusters are getting deleted.

**Comment by maxkochubey** [comment]
Jobs for corresponding clusters are created (in Jenkins GCP view).

**Comment by alexander-semenets** [comment]
We agreed to create per developer cluster with appropriate jobs for termination with individual schedule. 
Common clusters such as demo, ci, test should also have it's own destroy jobs but with common schedule 8PM GMT+3 for example.

**Comment by alexander-semenets** [comment]
done
