### ISSUE TITLE
Extensible template system software

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#97]
Now we are replacing consul-templates with our own k8s template system. Due that we need a tool capable to watch several information sources (K8S API, configMaps, etc) and produce configuration files from templates. 

It must be lightweight and modular to allow introduction of additional information sources.

**Comment by aliaksandr-d** [comment]
I found a problem with ltemplate in docker container. It's running in infiniteloop  in ubuntu, but in docker it's completed without errors.
