### ISSUE TITLE
Quickstart docs

### ISSUE THREAD

**Issue by mcdoker18** [legion-platform/legion#995]
Add the Legion quickstart documentation

**Comment by vlad-tokarev** [comment]
The desired docs sections:

- [ ] tutorial: authorization

- [ ] reference: legionctl (my suggest: generate from `click`)
- [ ] reference: Resource definition – Connection
- [ ] reference: Resource definition – ModelTraining
- [ ] reference: Resource definition – ModelPackaging
- [ ] reference: Resource definition – ModelDeployment

- [ ] section: Toolchain Model Training specification
- [ ] section: Toolchain Model Packaging specification
- [ ] reference: Docker REST Packaging Toolchain reference
